"""Transitional shim — 迁移到 src.perf.present.report_html."""
from .present.report_html import *  # noqa: F401,F403
from .present.report_html import (  # noqa: F401 — 显式 re-export 带下划线符号
    _parse_xctrace_table,
    _parse_mw_value,
    _safe_float,
    _fmt_time,
    _build_power_chart,
    _build_baseline_chart,
    _build_alert_timeline_chart,
    _build_dvt_process_chart,
    _build_dvt_system_chart,
    _build_battery_chart,
    _section_header,
    _section_gate,
    _section_power_summary,
    _section_charts,
    _section_dvt_process_table,
    _section_hotspots,
    _section_timeline,
    _section_syslog,
    _section_live_analysis,
    _section_baseline,
    _section_webkit_tree,
    _render_full_page,
)
